# Generated by Django 4.1.5 on 2023-01-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField(verbose_name='date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, to='friends.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to='friends.user')),
            ],
        ),
    ]
